### ISSUE TITLE
Is this project still actual?

### ISSUE THREAD

**Issue by jumasheff** [qmx/docker-avr-rust#2]
Hey, thank you for your effort. I am new to rust and AVR and wanted to ask if this project still actual and usable? The problem I want to solve is to keep my laptop as clean of artifacts as possible (don't want to install `brew install avr-binutils avr-gcc avrdude
` etc).

Thank you!

**Comment by qmx** [comment]
👋 this isn't active, thanks for the reminder, I'll archive the repo
